---
title: "Hierarchical spatial modelling for applied population and community ecology"
author:
  - "Jeffrey W. Doser, Marc K&eacute;ry<br>Michigan State University, Swiss Ornithological Institute"
date: "Workshop dates: 24-27 June 2024"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

## Course information

**Instructors**: Jeff Doser and Marc K&eacute;ry

**Teaching Assistant**: Gesa von Hirschheydt

**Venue**: Swiss Ornithological Institute, Sempach, Switzerland

**Computers**: Bring your own laptop with `R` installed and `R` packages `spOccupancy` and `spAbundance`

**Registration**: 500 francs (normal rate), 350 francs (student rate)

********

## Course description

Hierarchical models have been widely deployed for the modelling of species distribution and abundance, because they enable one to separately model the actual quantity of interest (e.g., presence/absence or abundance) from measurement errors commonly found in ecological data sets. When modelling species distributions/abundance across large spatial domains and/or using a large number of observed locations, accommodating spatial autocorrelation becomes increasingly important. Failing to account for measurement errors and/or residual spatial autocorrelation (i.e., remaining spatial autocorrelation after accounting for environmental covariates) can lead to biased and overly precise estimates, potentially jeopardizing scientific conclusions and management decisions based on such data sets.  

In this workshop, we present highly scalable approaches for hierarchical Bayesian spatial modelling of species distributions and abundance. This course focuses on practical implementation of hierarchical spatial models using the `spOccupancy` and `spAbundance` R packages. Course topics include: 

1. Introduction to hierarchical and spatial modelling
    + Hierarchical Bayesian models in ecology
    + Introduction to spatial statistics (e.g., kriging, Gaussian Processes)
    + Spatial modelling of big data
2. Spatial modelling of binary detection-nondetection data with `spOccupancy`
    + Single-species spatial occupancy models
    + Multi-species spatial occupancy models 
    + Joint species distribution models with imperfect detection
    + Spatially-varying coefficient occupancy models
3. Spatial modelling of count data with `spAbundance`
    + Single-species spatial GLMMs 
    + Single-species spatial N-mixture models
    + Single-species spatial hierarchical distance sampling models
    + Abundance-based joint species distribution models with imperfect detection

This intermediate-level course offers lecture, discussion, and hands-on exercises, with approximately 70% of the time on lectures and 30% of the time on exercises. We do not assume previous experience with Bayesian statistics, spatial statistics, or `spOccupancy/spAbundance`, although participants with basic knowledge of these areas will experience a gentler learning curve. We do require a good working knowledge of modern regression methods (e.g., linear models, generalized linear models) and of program R.  

********

## Tentative course schedule

The course will run from 9:00 to approximately 17:00-17:30, with lunch break from 13:00-14:00 and at least two coffee breaks at 10:30-11:00 and 15:30-16:00.

#### Monday 24 June 2024

+ 9:00--10:30 Introductions, hierarchical modelling in ecology and occupancy models (Jeff and Marc)
+ 11:00--13:00 Introduction to spatial statistics and `spOccupancy`/`spAbundance` (Jeff and exercise) 
+ 14:00--15:00 Introduction to spatial statistics and `spOccupancy`/`spAbundance` (Jeff and exercise)
+ 15:00--15:30 Modelling big spatial data (Jeff)
+ 16:00--17:00 Single-species spatial occupancy models (Jeff and exercise)
+ 17:00--17:30 Extra time for discussion, questions, etc.

#### Tuesday 25 June 2024

+ 9:00--9:45 Single-species spatial occupancy models (Jeff)
+ 9:45--10:30 Occupancy model survey design (Gesa)
+ 11:00--12:30 Application of single-species spatial occupancy models to Swiss birds (Marc)
+ 12:30--13:00 Multi-species occupancy models (Jeff)
+ 14:00--15:00 Joint species distribution models with imperfect detection (Jeff and exercise)
+ 15:00--15:30 Multi-species spatial occupancy models (Jeff)
+ 16:00--17:00 Multi-species spatial occupancy models (Jeff and exercise)
+ 17:00--17:30 Extra time for discussion, questions, etc.

#### Wednesday 26 June 2024

+ 9:00--10:30 Multi-season spatial occupancy models (Jeff and exercise)
+ 11:00--13:00 Multi-season spatial occupancy models and spatially varying trends (Jeff and exercise)
+ 14:00--15:30 Spatial GLMMs for modeling relative abundance or activity (Jeff and exercise)
+ 16:00--17:00 Introduction to N-mixture models (Marc)
+ 17:00--17:30 Extra time for discussion, questions, etc.

#### Thursday 27 June 2024

+ 9:00--10:30 Spatial N-mixture models (Jeff and exercise)
+ 11:00--11:30 Spatial N-mixture models (Jeff and exercise)
+ 11:30--13:00 Multi-species spatial N-mixture models (Jeff and exercise)
+ 14:00--15:30 Spatial hierarchical distance sampling models (Jeff and exercise)
+ 16:00--17:00 Multi-species spatial hierarchical distance sampling models (Jeff and exercise)
+ 17:00--17:30 Extra time for discussion, questions, etc.

## Application instructions

The application period is closed.

## GitHub Code Repository

All course lectures, code, and exercises can be found [here on the GitHub repository](https://github.com/doserjef/Switzerland24-Spatial-Workshop). 
